// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4L0QOrLh1CnJXKAMYh5Tl6LKXNz4svU',
    appId: '1:1092994237147:web:f88dde26ff6c230a9a02fe',
    messagingSenderId: '1092994237147',
    projectId: 'fotogram-clone',
    authDomain: 'fotogram-clone.firebaseapp.com',
    storageBucket: 'fotogram-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_oO7bojKT3vjpVken79dM1gYG9E_PZ4',
    appId: '1:1092994237147:android:8a49a9855f81c1389a02fe',
    messagingSenderId: '1092994237147',
    projectId: 'fotogram-clone',
    storageBucket: 'fotogram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ChNm-kyR80dEPRpWmVYp_9mAEqlJJLQ',
    appId: '1:1092994237147:ios:cad1d164cc0a80c09a02fe',
    messagingSenderId: '1092994237147',
    projectId: 'fotogram-clone',
    storageBucket: 'fotogram-clone.appspot.com',
    iosBundleId: 'com.example.igcloneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ChNm-kyR80dEPRpWmVYp_9mAEqlJJLQ',
    appId: '1:1092994237147:ios:cad1d164cc0a80c09a02fe',
    messagingSenderId: '1092994237147',
    projectId: 'fotogram-clone',
    storageBucket: 'fotogram-clone.appspot.com',
    iosBundleId: 'com.example.igcloneapp',
  );
}
